
###

GET http://localhost:3333/parques

###

POST http://localhost:3333/parques
Content-Type: application/json

{
    "nome": "Parque do Tio Zé",
    "local": "Av. É os Guri",
    "descricao": "Muito verde e calmo"
}

###

PUT http://localhost:3333/parques/207ba239-dea3-4c43-8bd1-a4d078e3ce5a
Content-Type: application/json

{
    "nome": "Parque do Tio Zé",
    "local": "Av. É os Guri",
    "descricao": "Muito verde e calmo"
}

###

DELETE http://localhost:3333/apiEco/207ba239-dea3-4c43-8bd1-a4d078e3ce5a
