
###

GET http://localhost:3333/parques

###

POST http://localhost:3333/parques
Content-Type: application/json

{
    "nome": "Parque do Tio Zé",
    "local": "Av. É os Guri",
    "descricao": "Muito verde e calmo"
}

###

PUT http://localhost:3333/parques/b186cf17-44ee-4e06-8f47-ac4d17cc5208
Content-Type: application/json

{
    "nome": "Parque do Tio José",
    "local": "Av. É os Guri",
    "descricao": "Muito verde e calmo"
}

###

DELETE http://localhost:3333/parques/99c17a2e-9d46-420c-9cad-b15183eab2b1
